In [3]:
import numpy as np
def hoga_ki_nahi(arr1,arr2):
  try:
    arr1+arr2
    return "Hoga"
  except ValueError:
    return "Nahi Hoga"

In [4]:
def hoga_ki_nahi(arr1,arr2):
  return #"Hoga"/"Nahi Hoga"

In [5]:
# Test your function here
def broadcast(ar1,ar2):
    d1=np.ndim(ar1)
    d2=np.ndim(ar2)
    s1=np.shape(ar1)
    s2=np.shape(ar2)
    if s1==s2:
        return "Hogia"
    else:
        for i in range(min(d1,d2)):
            if s1[-1-i]!=s2[-1-i]:
                if s1[-1-i]==1 or s2[-1-i]==1:
                    continue
                else:
                    return "Nahi hoga"
            else:
                continue
        return "Hoiga"

In [6]:
y=np.arange(168).reshape(4,2,3,7)
x=np.arange(6).reshape(2,3)

print(hoga_ki_nahi(x,y))
print(broadcast(x,y))


None
Nahi hoga


In [7]:
arr1=np.arange(40).reshape(8,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [8]:
arr2=np.random.randint(low=1, high=10000, size=10).reshape(2,5)
arr2

array([[9168, 2473, 7746, 7367, 8333],
       [ 309, 7362, 9030, 2462, 2377]])

In [9]:
np.percentile(arr1,25)

9.75

In [10]:
q1=arr1[:,0::2]

q1

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24],
       [25, 27, 29],
       [30, 32, 34],
       [35, 37, 39]])

In [11]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [12]:
# Q2. From arr1 fetch an array which would contain {0,2,4} {15,17,19} and {30,32,34} 
#ans2: 
# {0,2,4}-- 1st,3nd and 5th column, that is alternate column from 1st col.
# {0,15,30}-- 1st, 4th and 6th row, that is gap of 2 from 1st row
# combining both will give our result


q2=arr1[::3,::2]
q2

array([[ 0,  2,  4],
       [15, 17, 19],
       [30, 32, 34]])

In [13]:
arr2=np.random.randint(low=1, high=10000, size=10).reshape(2,5)
arr2

array([[9952, 1965, 4771,  120, 3891],
       [3165, 5640, 4177, 8980, 3661]])

In [14]:
max=arr2.max()
min=arr2.min()
narray=arr2/max
narray

array([[1.        , 0.19744775, 0.47940113, 0.01205788, 0.39097669],
       [0.31802653, 0.56672026, 0.41971463, 0.90233119, 0.36786576]])

In [15]:
# method 2:- 
# Ans:- Excepted answer for 
# Formula as given in above example explanation that is-- Xnew=(Xold-Xmin)/(Xmax-Xmin)
# Min-Max method--

mmarray=(arr2-min)/(max-min)
mmarray

array([[1.        , 0.18765256, 0.47304719, 0.        , 0.38354353],
       [0.30970301, 0.56143206, 0.41263222, 0.90113914, 0.36015053]])

In [16]:
# method 3(For normalisation):- Formula as given in above example explanation that is-- Xnew=(Xold-Mean)/(standard deviation)
# Z - score Method or standard Method--
"""This method is not considered for the above problen as this method is not used for normalise data in [0,1]"""

mean=arr2.mean()
std=arr2.std()
zarray=(arr2-mean)/std
zarray

array([[ 1.88596829, -0.94557213,  0.04920719, -1.59965904, -0.26276922],
       [-0.52014976,  0.35728389, -0.16137689,  1.54137617, -0.34430851]])

In [17]:
# Q4. How would you check if your numpy array has some missing values?

# Hint: Thoda research karo numpy me existing functions hai
#Ans4 - Research kr rhe hain 
# There is a function "np.isnan()".. but having problenm in passing arguments here like below
# "TypeError: ufunc 'isnan' not supported for the input types, 
#           and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''"
# Not as like isnan() but it check wether any dataa is missing or not


def check(arr):
    if np.nan in arr:
        return print("missing values")
    else:
        return print("no values missing")
check(narray)

no values missing


In [18]:
ar8=[1,2,np.nan,np.nan,90,88.0,90.0,np.nan]
check(ar8)

missing values


In [19]:
# After research foud out this function return an boolean array, 'True' represents data is missing  

np.isnan(ar8)

array([False, False,  True,  True, False, False, False,  True])

In [20]:
# Q5. Write a function which will accept 2 arguments.
# First: A 1D numpy array arr
# Second: An integer n {Please make sure n<=len(arr)}

# Output: The output should be the nth largest item out of the array

# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
#ans5:
#First sorted the array then return the last nth value of the array.

def nthmax(arr,n):
    if n<=len(arr):
        arr.sort()
        return arr[-n]
    else:
        raise IndexError('n should not exceed the length of the array {}, which is {}, \n The value of n was: {}'.format(arr,len(arr),n))
a1=np.array([10,18,11,45,78,32])
nthmax(a1,4)

18

In [21]:
#Test1:
a2=np.array([12,34,40,7,1,0])
nthmax(a2,3)

12

In [22]:
# Test2:
a3=np.array([12,34,40,7,1,0])
nthmax(a3,1)

40

In [23]:
arr1=np.arange(20).reshape(4,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [24]:
# Q1 Write a numpy code to swap col1([0,5,10,15]) with col4([3,8,13,18])
# Hint----> Fancy Indexing
import numpy as np
arr1= np.arange(20).reshape(4,5)
print("Original array:")
print(arr1)
arr1[:,[0, 3]] = arr1[:,[3, 0]]
print("\nAfter swapping arrays:")
print(arr1)

Original array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

After swapping arrays:
[[ 3  1  2  0  4]
 [ 8  6  7  5  9]
 [13 11 12 10 14]
 [18 16 17 15 19]]


In [25]:
# Q2 Write a numpy code to reverse the rows of arr1
# The output should be [15, 16, 17, 18, 19] as first row and [ 0,  1,  2,  3,  4] as last row
import numpy as np
arr1= np.arange(20).reshape(4,5)
print("Original array:")
print(arr1)
arr1[[0,3],:] = arr1[[3,0],:]
print("\nAfter swapping arrays:")
print(arr1)

Original array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

After swapping arrays:
[[15 16 17 18 19]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [ 0  1  2  3  4]]


In [26]:
arr2=np.array([[1,2,np.nan],[4,5,6],[np.nan,np.nan,9]])
arr2

array([[ 1.,  2., nan],
       [ 4.,  5.,  6.],
       [nan, nan,  9.]])

In [27]:
# Q3 Write a code to replace all the nan(missing values) of arr2 with the mean of arr2
import numpy as np
arr2=np.array([[1,2,np.nan],[4,5,6],[np.nan,np.nan,9]])
mean=arr2[np.isnan(arr2)!=True].mean()
arr2[np.isnan(arr2)==True]=mean
print(arr2)

[[1.  2.  4.5]
 [4.  5.  6. ]
 [4.5 4.5 9. ]]


In [28]:
arr3=np.random.randint(low=1,high=100,size=20).reshape(5,4)
arr3

array([[79, 75, 80, 23],
       [39, 58, 35, 98],
       [80, 93,  3, 82],
       [28, 96, 77, 90],
       [84, 65, 71, 97]])

In [29]:
# Q4 Write a code which can fetch all items from arr3 which are either greater than 25 or a multiple of 3
import numpy as np
arr3=np.random.randint(low=1,high=100,size=20).reshape(5,4)
arr3[(arr3>25) & (arr3%3==0)]

array([42, 27, 48, 96, 51, 30])

In [30]:
# Q5 Write a code to find the 10th, 25th, 50th(median) percentile of arr3
# Percentiles are a very important concept in Statistics. If you don't know about it refer the video below
# https://www.youtube.com/watch?v=Snf6Wpn-L4c
# Hint: to solve this function google np.percentile()
import numpy as np
arr = [81,48,60,54,81,45,93] 
print("arr : ", arr)  
print("50th percentile of arr : ",  
       np.percentile(arr, 50)) 
print("25th percentile of arr : ", 
       np.percentile(arr, 25)) 
print("10th percentile of arr : ", 
       np.percentile(arr, 10)) 


arr :  [81, 48, 60, 54, 81, 45, 93]
50th percentile of arr :  60.0
25th percentile of arr :  51.0
10th percentile of arr :  46.8
