In [1]:
# Dependency needed to install file 

!pip install xlrd
!pip install openpyxl

     ---------------------------------------- 96.5/96.5 kB 2.8 MB/s eta 0:00:00


In [2]:
# Import required library

import pandas as pd

After the import command, we now have access to a large number of pre-built classes and functions. This assumes the library is installed; in our lab environment all the necessary libraries are installed. One way pandas allow you to work with data is a dataframe. Let's go through the process to go from a comma separated values (.csv) file to a dataframe. This variable csv_path stores the path of the .csv, which is used as an argument to the read_csv function. The result is stored in the object df, this is a common short form used for a variable referring to a Pandas dataframe.

In [3]:
# Read data from CSV file

csv_path = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%204/data/TopSellingAlbums.csv'
df = pd.read_csv(csv_path)

In [4]:
# Print first five rows of the dataframe

df.head()

Artist                      Album  Released   Length  \
0  Michael Jackson                   Thriller      1982  0:42:19   
1            AC/DC              Back in Black      1980  0:42:11   
2       Pink Floyd  The Dark Side of the Moon      1973  0:42:49   
3  Whitney Houston              The Bodyguard      1992  0:57:44   
4        Meat Loaf            Bat Out of Hell      1977  0:46:33   

                         Genre  Music Recording Sales (millions)  \
0               pop, rock, R&B                              46.0   
1                    hard rock                              26.1   
2             progressive rock                              24.2   
3               R&B, soul, pop                              27.4   
4  hard rock, progressive rock                              20.6   

   Claimed Sales (millions) Released.1 Soundtrack  Rating  
0                        65  30-Nov-82        NaN    10.0  
1                        50  25-Jul-80        NaN     9.5  
2                        45  01-Mar-73        NaN     9.0  
3                        44  17-Nov-92          Y     8.5  
4                        43  21-Oct-77        NaN     8.0

We use the path of the excel file and the function read_excel. The result is a data frame as before:

In [5]:
# Read data from Excel File and print the first five rows

xlsx_path = 'https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%204/Datasets/TopSellingAlbums.xlsx'

df = pd.read_excel(xlsx_path)
df.head()

Artist                      Album  Released    Length  \
0  Michael Jackson                   Thriller      1982  00:42:19   
1            AC/DC              Back in Black      1980  00:42:11   
2       Pink Floyd  The Dark Side of the Moon      1973  00:42:49   
3  Whitney Houston              The Bodyguard      1992  00:57:44   
4        Meat Loaf            Bat Out of Hell      1977  00:46:33   

                         Genre  Music Recording Sales (millions)  \
0               pop, rock, R&B                              46.0   
1                    hard rock                              26.1   
2             progressive rock                              24.2   
3               R&B, soul, pop                              27.4   
4  hard rock, progressive rock                              20.6   

   Claimed Sales (millions) Released.1 Soundtrack  Rating  
0                        65 1982-11-30        NaN    10.0  
1                        50 1980-07-25        NaN     9.5  
2                        45 1973-03-01        NaN     9.0  
3                        44 1992-11-17          Y     8.5  
4                        43 1977-10-21        NaN     8.0

In [6]:
# Access to the column Length

x = df[['Length']]
x

Length
0  00:42:19
1  00:42:11
2  00:42:49
3  00:57:44
4  00:46:33
5  00:43:08
6  01:15:54
7  00:40:01

In [7]:
# Get the column as a series

x = df['Length']
x

0    00:42:19
1    00:42:11
2    00:42:49
3    00:57:44
4    00:46:33
5    00:43:08
6    01:15:54
7    00:40:01
Name: Length, dtype: object

In [8]:
# Get the column as a dataframe

x = df[['Artist']]
type(x)

pandas.core.frame.DataFrame

You can do the same thing for multiple columns; we just put the dataframe name, in this case, df, and the name of the multiple column headers enclosed in double brackets. The result is a new dataframe comprised of the specified columns

In [10]:
# Access to multiple columns

y = df[['Artist','Length','Genre']]
y

Artist    Length                        Genre
0  Michael Jackson  00:42:19               pop, rock, R&B
1            AC/DC  00:42:11                    hard rock
2       Pink Floyd  00:42:49             progressive rock
3  Whitney Houston  00:57:44               R&B, soul, pop
4        Meat Loaf  00:46:33  hard rock, progressive rock
5           Eagles  00:43:08   rock, soft rock, folk rock
6         Bee Gees  01:15:54                        disco
7    Fleetwood Mac  00:40:01                    soft rock

In [11]:
# Access the value on the first row and the first column

df.iloc[0, 0]

'Michael Jackson'

In [12]:
# Access the value on the second row and the first column

df.iloc[1,0]

'AC/DC'

In [13]:
# Access the value on the first row and the third column

df.iloc[0,2]

1982

In [14]:
# Access the value on the second row and the third column
df.iloc[1,2]

1980

In [15]:
# Access the column using the name

df.loc[0, 'Artist']

'Michael Jackson'

In [16]:
# Access the column using the name

df.loc[1, 'Artist']

'AC/DC'

In [17]:
# Access the column using the name

df.loc[0, 'Released']

1982

In [18]:
# Access the column using the name

df.loc[1, 'Released']

1980

In [19]:
# Slicing the dataframe

df.iloc[0:2, 0:3]

Artist          Album  Released
0  Michael Jackson       Thriller      1982
1            AC/DC  Back in Black      1980

In [20]:
# Slicing the dataframe using name

df.loc[0:2, 'Artist':'Released']

Artist                      Album  Released
0  Michael Jackson                   Thriller      1982
1            AC/DC              Back in Black      1980
2       Pink Floyd  The Dark Side of the Moon      1973

You can perform slicing using both the index and the name of the column

In [21]:
df.iloc[1, 2]

1980

In [22]:
new_index=['a','b','c','d','e','f','g','h']
df_new=df
df_new.index=new_index
df_new.loc['a', 'Artist']
df_new.loc['a':'d', 'Artist']

a    Michael Jackson
b              AC/DC
c         Pink Floyd
d    Whitney Houston
Name: Artist, dtype: object

In [23]:
a = ["0", 1, "two", "3", 4]

In [24]:
print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: two
a[3]: 3
a[4]: 4


What is Numpy?

NumPy is a Python library used for working with arrays, linear algebra, fourier transform, and matrices.A numpy array is similar to a list. NumPy stands for Numerical Python and it is an open source project.The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

NumPy is usually imported under the np alias.

It's usually fixed in size and each element is of the same type. We can cast a list to a numpy array by first importing numpy

In [25]:
import numpy as np 

In [26]:
a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [27]:
# Print each element

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


In [28]:
print(np.__version__)

1.23.5


In [29]:
# Check the type of the array

type(a)

numpy.ndarray

As numpy arrays contain data of the same type, we can use the attribute "dtype" to obtain the data type of the array’s elements. In this case, it's a 64-bit integer

In [30]:
# Check the type of the values stored in numpy array

a.dtype

dtype('int32')

In [31]:
b = np.array([3.1, 11.02, 6.2, 213.2, 5.2])
type(b)

numpy.ndarray

In [32]:
b.dtype

dtype('float64')

In [48]:
c = np.array([20, 1, 2, 3, 4])

In [49]:
c[0] = 100
c

array([100,   1,   2,   3,   4])

In [50]:
# Assign the 5th element to 0

c[4] = 0
c

array([100,   1,   2,   3,   0])

Like lists, we can slice the numpy array. Slicing in python means taking the elements from the given index to another given index.

We pass slice like this: [start:end].The element at end index is not being included in the output.

We can select the elements from 1 to 3 and assign it to a new numpy array d as follows

In [51]:
# Slicing the numpy array

d = c[1:4]
d

array([1, 2, 3])

In [52]:
# Set the fourth element and fifth element to 300 and 400

c[3:5] = 300, 400
c

array([100,   1,   2, 300, 400])

We can also define the steps in slicing, like this: [start:end:step].

In [38]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


If we don't pass start its considered 0

In [39]:
print(arr[:4])

[1 2 3 4]


If we don't pass end it considers till the length of array.

In [40]:
print(arr[4:])

[5 6 7]


If we don't pass step its considered 1

In [41]:
print(arr[1:5:])

[2 3 4 5]


In [42]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr[1:8:2])

[2 4 6 8]


Similarly, we can use a list to select more than one specific index. The list select contains several values

In [44]:
select = [0, 2, 3, 4]
select

[0, 2, 3, 4]

In [53]:
c



array([100,   1,   2, 300, 400])

In [54]:
# Use List to select elements

d = c[select]
d

array([100,   2, 300, 400])

In [55]:
c[select] = 100000
c

array([100000,      1, 100000, 100000, 100000])

In [56]:
a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [57]:
# Get the size of numpy array

a.size

5

In [58]:
# Get the number of dimensions of numpy array

a.ndim

1

The next two attributes will make more sense when we get to higher dimensions but let's review them. The attribute ndim represents the number of array dimensions, or the rank of the array. In this case, one

The attribute shape is a tuple of integers indicating the size of the array in each dimension

In [59]:
# Get the shape/size of numpy array

a.shape

(5,)

In [60]:
b = np.array([10, 20, 30, 40, 50, 60, 70])

In [62]:
b.size



7